# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52569a2fc53527d71d5fefb6322f6b96869055de0c1fd3de56d21846b808c7d4750f9c9bc34d5e42c0d0d513e55e8ed342e1ba9c4114e39d93a11480277f38ea

test:
  secret_key_base: 5a4d53a5e70ef70394a36131927cd0c6f75e1053dc1c1283ba4e18ea2d0f3c8919826ddfc8a7e308eb7d4cb8e119ad800506ec72d179a5328771b847142f12e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
